name: Sync

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build
    steps:
      - name: Import ssh private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Git config
        run: |
          git config --global user.name "Ryanjie"
          git config --global user.email "4646-Ryanjie@users.noreply.test50k.gitlab.cn"
          git config --global core.sshCommand "/usr/bin/ssh -i ~/.ssh/id_rsa"
          # https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository/13364116#13364116
          # ssh-keygen -R jihulab.com
          ssh-keyscan -t rsa jihulab.com >> ~/.ssh/known_hosts
      - name: Sync
        run: |
          # set -euxo pipefail

          CURRENT_DIR="$(pwd)"
          DATE="$(echo $(TZ=UTC date '+%Y-%m-%d %H:%M:%S'))"
          USER=$(whoami)

          git clone -q --depth=1 git@jihulab.com:Ryanjie/Tian.git "${CURRENT_DIR}/tian-cn"
          git clone -q --depth=1 https://Ryanjiena:${github_token}@github.com/Ryanjiena/fantastic-bucket.git "${CURRENT_DIR}/fantastic"

          cd ${CURRENT_DIR}/fantastic/bucket/
          # sed -i 's|\(https://github.com/.*/releases/download\)|https://ghproxy.com/\1|g;s|\(https://github.com/.*/archive\)|https://ghproxy.com/\1|g;s|\(https://raw.githubusercontent.com/\)|https://ghproxy.com/\1|g' *json

          cd ${CURRENT_DIR}/tian-cn/
          if [ -d "bucket" ]; then
              rm -rf bin bucket scripts README.md
          fi

          cp ${CURRENT_DIR}/fantastic/bin/* ${CURRENT_DIR}/tian-cn/bin/ -f
          cp ${CURRENT_DIR}/fantastic/bucket/* ${CURRENT_DIR}/tian-cn/bucket/ -f
          cp ${CURRENT_DIR}/fantastic/scripts/* ${CURRENT_DIR}/tian-cn/scripts/ -r -f
          cp ${CURRENT_DIR}/fantastic/README.md ${CURRENT_DIR}/tian-cn/README.md -f

          git add . && git commit -m "Sync by: ${USER}, at: ${DATE}"
          git push -u origin main

      - name: Remove ssh private key
        run: rm -f ~/.ssh/id_rsa
